"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _template_preview from './template-preview.bones.json'
import _project_preview from './project-preview.bones.json'
import _privacy_settings from './privacy-settings.bones.json'

configureBoneyard({"color":"#1f1f1f","darkColor":"#1f1f1f","animate":"shimmer","shimmerColor":"#2a2a2a","darkShimmerColor":"#2a2a2a","speed":"1.5s","transition":300})

registerBones({
  "template-preview": _template_preview,
  "project-preview": _project_preview,
  "privacy-settings": _privacy_settings,
})
