import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Scaffold files added to every ZIP download to make it a real Next.js project.
 * These are NOT generated by the AI — they're boilerplate.
 */
const SCAFFOLD_FILES = {
  'package.json': (appName, deps) => JSON.stringify({
    name: appName.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      next: '^14.0.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      ...deps
    },
    devDependencies: {
      typescript: '^5',
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      tailwindcss: '^3.4.0',
      postcss: '^8',
      autoprefixer: '^10'
    }
  }, null, 2),

  'next.config.js': () => `/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
`,

  'tsconfig.json': () => JSON.stringify({
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] }
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules']
  }, null, 2),

  'tailwind.config.ts': () => `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`,

  'postcss.config.js': () => `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,

  '.gitignore': () => `# dependencies
/node_modules
/.pnp
.pnp.js

# next.js
/.next/
/out/

# misc
.DS_Store
*.pem
.env*.local
`,

  'README.md': (appName) => `# ${appName}

Built with [StackForge](https://stackforge.dev)

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.
`,
};

/**
 * Detect npm packages used in the generated files.
 */
function detectDependencies(files) {
  const deps = {};
  const importRegex = /from\s+['"]([^'"./][^'"]*)['"]/g;
  const allowedDeps = {
    'lucide-react': 'latest',
    'framer-motion': 'latest',
    'clsx': 'latest',
    'tailwind-merge': 'latest',
    'recharts': 'latest',
    'react-hot-toast': 'latest',
    'zustand': 'latest',
    'date-fns': 'latest',
    'zod': 'latest',
    '@radix-ui/react-dialog': 'latest',
    '@radix-ui/react-dropdown-menu': 'latest',
    '@radix-ui/react-select': 'latest',
  };

  Object.values(files).forEach(file => {
    const content = typeof file === 'string' ? file : file?.content || '';
    let match;
    while ((match = importRegex.exec(content)) !== null) {
      const fullPkg = match[1];
      if (fullPkg.startsWith('@/')) continue; // Skip path aliases
      const pkg = fullPkg.startsWith('@')
        ? fullPkg.split('/').slice(0, 2).join('/')
        : fullPkg.split('/')[0];
      if (allowedDeps[pkg]) deps[pkg] = allowedDeps[pkg];
    }
  });

  return deps;
}

/**
 * Download project files as a ZIP file with proper Next.js project structure.
 * @param {Object} files - Map of { path: { content: string } }
 * @param {string} appName - Name of the project
 */
export async function downloadProjectAsZip(files, appName = 'my-app') {
  const zip = new JSZip();

  // 1. Add generated files
  Object.entries(files).forEach(([path, file]) => {
    const cleanPath = path.startsWith('/') ? path.slice(1) : path;
    const content = typeof file === 'string' ? file : file?.content || '';
    zip.file(cleanPath, content);
  });

  // 2. Add scaffold files (only if not already generated)
  const existingPaths = Object.keys(files).map(p => p.startsWith('/') ? p.slice(1) : p);
  const deps = detectDependencies(files);

  Object.entries(SCAFFOLD_FILES).forEach(([name, generator]) => {
    if (!existingPaths.includes(name)) {
      zip.file(name, generator(appName, deps));
    }
  });

  // 3. Generate and save
  const blob = await zip.generateAsync({ type: 'blob' });
  const safeName = appName.toLowerCase().replace(/[^a-z0-9-]/g, '-') || 'project';
  saveAs(blob, `${safeName}.zip`);
}
